version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      MONGO_HOST: localhost
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: Secret1234
      MONGO_INITDB_DATABASE: notification-db-webflux-docker-local
    ports:
      - "27017:27017"

  myappwebflux:
    image: 'fabiohpsouza/notif-appwebflux:0.0.5'
    container_name: myappwebflux
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://adminUser:Secret1234@localhost:27017/notification-db-webflux-docker-local
    ports:
      - "8352:8352"
    depends_on:
      - mongodb