version: '3.9'
services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_DB: db_notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hnkx@7701
    ports:
      - "5432:5432"

  app:
    image: 'fabiohpsouza/notifications-app:0.1.6'
    container_name: app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hnkx@7701
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_notifications
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Hnkx@7701
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8006:8005"
    depends_on:
      - db

