version: '3.9'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: fabiohpsouza
      MONGO_INITDB_ROOT_PASSWORD: Hnkx@7701
      MONGO_INITDB_DATABASE: notification-db-webflux-docker-local
    ports:
      - "27017:27017"
    networks:
      - notifications_default

  myappwebflux:
    image: 'fabiohpsouza/notif-appwebflux:0.1.11'
    container_name: myappwebflux
    environment:
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_URI: mongodb://fabiohpsouza:Hnkx@7701@mongo:27017/notification-db-webflux-docker-local?authSource=admin
    ports:
      - "8352:8352"
    depends_on:
      - mongo
    networks:
      - notifications_default

networks:
  notifications_default:
    driver: bridge