services:
  mongo:
    image: mongo:7.0.9
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: fabiohpsouza
      MONGO_INITDB_ROOT_PASSWORD: Hnkx@7701
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"

  myappwebflux:
    image: 'fabiohpsouza/notif-appwebflux:0.0.3'
    container_name: myappwebflux
    environment:
      MONGO_USERNAME: fabiohpsouza
      MONGO_PASSWORD: Hnkx@7701
      MONGO_DB: test
    ports:
      - "8352:8352"
    depends_on:
      - mongo