version: '3.9'
services:
  myappwebflux:
    image: 'fabiohpsouza/notif-appwebflux:0.0.7'
    container_name: myappwebflux
    environment:
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: authSource=admin
      SPRING_DATA_MONGODB_URI: mongodb://adminUser:Secret1234@mongo:27017/notification-db-webflux-docker-local?authSource=admin
    ports:
      - "8353:8352"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: Secret1234
      MONGO_INITDB_DATABASE: notification-db-webflux-docker-local
    ports:
      - "27017:27017"